apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-main-app-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: go-main-app-svc
          servicePort: 3333