apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-main-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-main-app
  template:
    metadata:
      labels:
        app: go-main-app
    spec:
      containers:
        - name: go-main-app
          image: pasiol/go-main-app:latest